### PR TITLE
Make separate batchPrice API call

### PR DESCRIPTION
**Pull request by JZL**
Hi,

Really enjoyed your repo, it helped me find a new laptop :)

I had hourly notifications for a certain type I was looking for, and noticed that sometimes the price would be different compared to the website's price. Tracking it down, I found there's a separate URL `https://openapi.lenovo.com/us/outletus/en/detail/price/batch/get` which had that newer price. Consistently, for some SKU's, it was cheaper for up to a day and then the 'original' logaze price would converge to that cheaper price. I don't know if double the requests is worth a temporarily more accurate price.

Here I overwrite the 'original' `:price`, it could also be separated into a different column name, although I never found a reason to have the original price.

I also don't really know closure, was just hacking it together. So the line
```
(get-in parsed ["data" product-number 4])))
```
could maybe use `keywordize` and be cleaner. Maybe additional rate limiting is also necessary.

Oh, also this would make `:percentage-savings` inaccurate, I just never used it in my checks. I can try to figure out clojure enough to recalculate it

### CODE REVIEW

**Comment by JZL** [comment]
Unrelated but it helpful to me -- I wonder if the faq could point people towards https://psref.lenovo.com/ . This is an amazing resource for technical users to understand the actual laptop specs and true caveats.

For instance, many of the (intel) Thinkpad laptops have 1 soldered ram and one replaceable slot. So logaze might say the ram is soldered at 8GB, but you could easily add/replace the other slot's memory and increase the memory to 8+32 GB easily and cheaply. (With some caveats about dual channel mode, etcm which you can find in the manual there)

**Comment by ackerleytng** [comment]
I'm happy this helped you, and thank you for your contribution :)

How did you set up notifications? Did you build something or was it a Lenovo feature? 

Let me try to understand what happens: 

+ Is the price in the notification the price you could buy the laptop at if you bought the laptop through the notification? 
+ Does Lenovo update the `:original` price? I thought 
`:original` was the price before discount, and I meant to keep it in the data just for completion and for someone who might want to know how much the percentage discount was, like maybe they wanted to get a laptop that was most discounted. If it's the price before discount or the original price the laptop was bring sold at, I wasn't expecting `:original` to change at all.

Thanks for https://psref.lenovo.com/, I'll find a place on logaze to put that.

**Comment by JZL** [comment]
Hi,

Oh sorry, I mentioned the notification only to say how I caught this somewhat-ephemeral price difference, it's unrelated to this PR [1].

And sorry again for my confusing terminology. Because I didn't use the frontend, just the scraper, I only ever looked at a subset of the json fields. So I had a name collision in my above message on `original` :-(. When I said
> 'original' price

 I meant the `price` field without this PR, in conrast to the 'changed' price field after this PR. Which is entirely unrelated to `:original` the key. So confusing!

The way I found this was by having my email notifications from [1] (based solely on the jsonblobs), and happening to click through to a product which has this price discrepancy. So saw the `:price` field in the (pre-PR) json was higher than the price on the website.

In my testing, I didn't overwrite the `:price` key, and kept the pre- and post- PR `price`'s separate. And saw this patten happen many times, where the post-PR price goes lower for a day or so before the pre-PR price caught up



[1] - I didn't use the frontend just the backend jsonblobs. I used a little script to filter the json's to only the models/types I was interested in, and fed it through [urlwatch](https://urlwatch.readthedocs.io/en/latest/) to get hourly emails on changes

**Comment by ackerleytng** [comment]
urlwatch is cool! Glad this helped you. I'm kinda busy right now, I'll definitely take a closer look at this PR soon! Thanks again!

**Review by ackerleytng — APPROVED** [review]
After finding some time to read your code, I understand now! 

Thank you again for your contribution! Thank you for taking the time to understand the difference between the price logaze was reporting and the price you see on the website, and thanks for taking the time to write a PR, I really appreciate it!

I have a few (clojure) things to point out, but I'm going to merge the changes anyway and then refactor.

1. Clojure/lisps like using kebab-case for variable and function names like `new-price` rather than `newPrice`.
2. Not using `keywordize` is fine, I like your use of `get-in` since `product-number` is part of the path to get to the data we need.
3. I'll add a small change to update `:final-price` only if there's a value returned from the batch/price API.

**Comment by JZL** [comment]
Hooray 🎉, what a nice response.
All that sounds great to me, I'm using the laptop I got from this now!

**Pull request merged**
